const String OnboardingViewRoute = "OnboardingView";
const String LoginViewRoute = "LoginView";
const String SignUpViewRoute = "SignUp";
const String HomeViewRoute = "HomeView";
const String ProfileViewRoute = "ProfileView";
const String PostsViewRoute = "PostsView";
const String TasksViewRoute = "TasksView";
const String CreatePostViewRoute = "CreatePostView";
const String BlacklistViewRoute = "BlacklistView";
// Generate the views here