const String OnboardingViewRoute = "OnboardingView";
const String LoginViewRoute = "LoginView";
const String HomeViewRoute = "HomeView";
const String BrowseViewRoute = "BrowseView";
const String ProfileViewRoute = "ProfileView";
const String PostsViewRoute = "PostsView";
const String TasksViewRoute = "TasksView";
const String CreatePostViewRoute = "CreatePostView";
const String ViewPostViewRoute = "ViewPostView";
const String BlacklistViewRoute = "BlacklistView";
const String SearchViewRoute = "SearchView";
const String ChatViewRoute = "ChatView";
// Generate the views here